### ISSUE TITLE
Won't block my sites at specified time

### ISSUE THREAD

**Issue by sim2100** [andreasgrill/auto-selfcontrol#20]
Thank you for making this!

Problem: I followed the installation instructions, but at the specified time, I can still access my blocked sites

My settings are this:

{
    "username": "MY_USERNAME",
    "selfcontrol-path": "/Applications/SelfControl.app",
    "host-blacklist": [
        "twitter.com",
        "reddit.com"
    ],
    "block-schedules":[
        {
            "weekday": 1,
            "start-hour": 17,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 2
        },
        {
            "weekday": 1,
            "start-hour": 17,
            "start-minute": 4,
            "end-hour": 17,
            "end-minute": 6
        },
    ]
}

when i install the python file, i get this:

Traceback (most recent call last):
  File "auto-selfcontrol.py", line 10, in <module>
    from Foundation import NSUserDefaults, CFPreferencesSetAppValue, CFPreferencesAppSynchronize, NSDate
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/Foundation/__init__.py", line 8, in <module>
    import objc
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/__init__.py", line 28, in <module>
    from objc._bridgesupport import *
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_bridgesupport.py", line 13, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

Notice that it ends in an error - maybe that is a reason why?

**Comment by andreasgrill** [comment]
Did you use the following command to install Auto-SelfControl:
```sudo /usr/bin/python auto-selfcontrol.py```

Or did you use a custom python version?

**Comment by username1761** [comment]
Hey Andreas - i just used your instructions - i.e. sudo /usr/bin/python auto-selfcontrol.py

**Comment by andreasgrill** [comment]
Could you tell me what OSX version you are using?

**Comment by username1761** [comment]
OSX Yosemite Version 10.10

**Comment by username1761** [comment]
OSX Yosemite Version 10.10

**Comment by gregorydm** [comment]
Didn't you simply forget to set your username in:
`"username": "MY_USERNAME",` ?

**Comment by gregorydm** [comment]
Didn't you simply forget to set your username in:
`"username": "MY_USERNAME",` ?

**Comment by gregorydm** [comment]
@username1761 
Didn't you simply forget to set your username in:
`"username": "MY_USERNAME", `?

You can find your Mac OS username by opening terminal.app and typing `whoami` or just by looking at the name of your home folder.

**Comment by username1761** [comment]
thanks a lot dude - you're right, i missed the username.

I put that in correctly, and it still doesn't work.

When i install the python file, i get this:

Traceback (most recent call last):
  File "auto-selfcontrol.py", line 10, in <module>
    from Foundation import NSUserDefaults, CFPreferencesSetAppValue, CFPreferencesAppSynchronize, NSDate
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/Foundation/__init__.py", line 8, in <module>
    import objc
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/__init__.py", line 28, in <module>
    from objc._bridgesupport import *
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_bridgesupport.py", line 13, in <module>
    import pkg_resources
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)


Here's what my config looks like now:


{
    "username": "djzcomputer1",
    "selfcontrol-path": "/Applications/SelfControl.app",
    "host-blacklist": [
        "twitter.com",
        "reddit.com",
		"facebook.com"
    ],
    "block-schedules":[
        {
            "weekday": 1,
            "start-hour": 17,
            "start-minute": 15,
            "end-hour": 17,
            "end-minute": 16
        },
        {
            "weekday": 2,
            "start-hour": 17,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 3
        },
        {
            "weekday": 3,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 4,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 5,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 6,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        },
        {
            "weekday": 7,
            "start-hour": 8,
            "start-minute": 0,
            "end-hour": 17,
            "end-minute": 0
        }
    ]
}

**Comment by gregorydm** [comment]
Did you already try this from the troobleshooting section in README.md?  :

> ImportError: No module named Foundation
> 
> If you've installed Python using HomeBrew, you'll need to run Auto-SelfControl with the original Python installation from OS X:
> 
> sudo /usr/bin/python auto-selfcontrol.py
> There are also other options, including installing pyobjc on your brewed Python (pip install pyobjc). See this thread for alternative solutions.

**Comment by andreasgrill** [comment]
Could you try this?
https://github.com/nylas/sync-engine/issues/432#issuecomment-275931718

**Comment by username1761** [comment]
yes will do. will report back.


---
Michael G. Simpson
mgsimpson1@gmail.com
M: 203-506-6029 <(203)%20506-6029>
