### ISSUE TITLE
Wrong version of PyObjC C API

### ISSUE THREAD

**Issue by trangthule** [andreasgrill/auto-selfcontrol#23]
Hi Andreas, I'm having this problem after running sudo /usr/bin/python auto-selfcontrol.py:

Traceback (most recent call last):
  File "auto-selfcontrol.py", line 10, in <module>
    from Foundation import NSUserDefaults, CFPreferencesSetAppValue, CFPreferencesAppSynchronize, NSDate
  File "/Library/Python/2.7/site-packages/pyobjc_framework_Cocoa-3.2.1-py2.7-macosx-10.12-intel.egg/Foundation/__init__.py", line 9, in <module>
    import CoreFoundation
  File "/Library/Python/2.7/site-packages/pyobjc_framework_Cocoa-3.2.1-py2.7-macosx-10.12-intel.egg/CoreFoundation/__init__.py", line 22, in <module>
    import CoreFoundation._CoreFoundation
**RuntimeError: Wrong version of PyObjC C API (got 19, expected 20)**
 Hope you can help.

**Comment by AndriyLin** [comment]
I am seeing the same issue on my mac (10.12.6).
And this is likely due to dependency issue when running `setup.py`:

```
......
Processing dependencies for auto-selfcontrol==1.0
error: pyobjc-core 2.5.1 is installed but pyobjc-core==4.0b1 is required by set(['pyobjc'])
```

I tried to upgrade pyobjc and pyobjc-core in particular using pip, but the latest version on pip seems to be 3.2.1.

Any suggestions on this?
Thanks.

**Comment by ssent1** [comment]
I installed **PyObjC Version 4.0** using easy_install.
`$ easy_install -U pyobjc-core`
This was enough for me, but you might also have to install:
`$ easy_install -U pyobjc`

> SelfControl  started.

«src: [Installing PyObjC](https://pythonhosted.org/pyobjc/install.html) »

**Comment by AndriyLin** [comment]
@ssent1 Thanks but that doesn't work for me. I still have the pyobjc version mismatch problem following what you said.

But strangely I tried running using python3 and the problem is gone. Although using python3 to run the app would raise error while using python2 to run the app still exposes this pyobjc mismatch issue (RuntimeError: Wrong version of PyObjC C API (got 19, expected 20).

**Comment by nickjmorrow** [comment]
@AndriyLin were you ever able to get it to work?

**Comment by AndriyLin** [comment]
@nickjmorrow No, it complains as usual, so I stopped trying and removed the app.. 😓

**Comment by oliverswitzer** [comment]
Having the same issue. Still occurring after running 

```
$ easy_install -U pyobjc-core
$ easy_install -U pyobjc
```

**Comment by jouhoff** [comment]
managed to fix it, start over -> manual install req. specific versions with previous xcode version, solved it.
